### ISSUE TITLE
Determine the nature of the permssion error preventing bulk upload via the gui

### ISSUE THREAD

**Issue by RHVDM** [MAEASaM/MAEASaM-resource-models#2]

**Comment by dir21** [comment]
See entry for '2024-01-29' (and the preceding entry '2024-01-27') in 'Google Drive:/Systems_Administration/Documentation/CHANGELOG_hsps-arches-maeasam-prod_iaas.txt' but to cut a long story short, you need to make sure that the users in the project-related config files for supervisors are correct.

Too superstitious to actually close this ticket.
